### ISSUE TITLE
클럽 관리자 페이지, 리스트에서 텍스트를 클릭해야만 이벤트가 활성화 됨

### ISSUE THREAD

**Issue by dlgochan** [paranArena/RTU-iOS-App#6]

**Comment by 99Page** [comment]
어떤 이슈인지 잘 감이 안오네요.

**Comment by dlgochan** [comment]
![IMG_2753](https://user-images.githubusercontent.com/90930393/190364890-ead6060b-d85f-4f5a-b7f8-4e9bff94179d.PNG)
여기서 텍스트를 정확히 눌러야만 이벤트가 발생한다는 말이였습니다.

사용하는데에 그렇게 큰 불편은 주지 않지만 좀 옆쪽?을 눌러도 버튼이 눌리도록 하면 좋을 것 같아서 남겼습니다.

**Comment by 99Page** [comment]
solve
